config/routes.rb
BolfTracker::Application.routes.draw do
	resources :players
	
	resources :games do
		resources :scores
	end

	root :to => "home#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :scores
    
    attr_reader :winning_score, :winner
    
    def calculate_fields
        @winning_score = Score.where(:game_id => id).maximum("points")
        @winner = Score.where(:game_id => id).where(:points => winning_score).first
    end
end

app/models/player.rb
class Player < ActiveRecord::Base
    has_many :scores
  
    attr_reader :games_won, :num_of_games, :points
  
    def games_lost
        num_of_games - games_won
    end

    def points_per_game
        if (num_of_games.nil? or num_of_games.zero?)
            return 0
        else
            return (points.to_f / num_of_games.to_f).ceil
        end
    end
  
    def winning_pct
        if (num_of_games.nil? or num_of_games.zero?)
            return 0
        else
            return games_won.to_f / num_of_games.to_f
        end
    end
  
    def calculate_fields(year, month)
        @games_won = 0
        
        date_range = (Date.new(year, month, 01) - 1.day)..(Date.new(year, month, 01) + 1.month)
        
        @games = Game.where(:created_at => date_range)
        @games.each do |g|
            g.calculate_fields
            if g.winner.player.id == id
                @games_won += 1
            end
        end
        
        @num_of_games = 0
        @points = 0
        
        @num_of_games = Game.joins(:scores).where(:scores => { :player_id => id }, :created_at => date_range).count
        @points = Game.joins(:scores).where(:scores => { :player_id => id }, :created_at => date_range).sum("points")
    end
end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :game
	belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    # GET /games  
    def index
        @games = Game.where(:created_at => (Date.new(2011,01,01)..Date.new(2011,02,01)))
        #Game.find(:all, :order => "id desc", :limit => 10)

        @games.each do |g|
            g.calculate_fields
        end
    end

    # GET /games/1  
    def show
        @game = Game.find(params[:id])
        @game.calculate_fields

        @players = Player.all
        @players.sort! { |a,b| a.name <=> b.name }
    end

    # GET /games/new  
    def new
        @game = Game.new
    end

    # GET /games/1/edit
    def edit
        @game = Game.find(params[:id])
    end

    # POST /games  
    def create
        @game = Game.new(params[:game])

        if @game.save
            redirect_to(@game, :notice => 'Game was successfully created.')        
        else
            render :action => "new"        
        end      
    end

    # PUT /games/1  
    def update
        @game = Game.find(params[:id])

        if @game.update_attributes(params[:game])
            redirect_to(@game, :notice => 'Game was successfully updated.')        
        else
            render :action => "edit"        
        end
    end

    # DELETE /games/1  
    def destroy
        @game = Game.find(params[:id])
        @game.destroy

        @scores = Score.where(:game_id => params[:id])

        @scores.each do |score|
            score.destroy
        end

        redirect_to(games_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
        @current_month = Date.today
        @previous_month = Date.today - 1.month
        
        @current_month_players = Player.all

        @current_month_players.each do |p|
            p.calculate_fields(Date.today.year, Date.today.month)
        end
        
        @final_cur_month_players = @current_month_players.find_all { |p| p.num_of_games > 0 }
        @final_cur_month_players.sort! { |a,b| 
            (b.winning_pct <=> a.winning_pct).nonzero? || 
            (b.points_per_game <=> a.points_per_game).nonzero? ||
            (b.points <=> a.points) }
            
        @prev_month_players = Player.all
        
        @prev_month_players.each do |p|
            p.calculate_fields(@previous_month.year, @previous_month.month)
        end
        
        @final_prev_month_players = @prev_month_players.find_all { |p| p.num_of_games > 0 }
        @final_prev_month_players.sort! { |a,b| 
            (b.winning_pct <=> a.winning_pct).nonzero? || 
            (b.points_per_game <=> a.points_per_game).nonzero? ||
            (b.points <=> a.points) }
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    # GET /players  
    def index
        @players = Player.all
    end

    # GET /players/1  
    def show
        @player = Player.find(params[:id])
    end

    # GET /players/new  
    def new
        @player = Player.new
    end

    # GET /players/1/edit
    def edit
        @player = Player.find(params[:id])
    end

    # POST /players  
    def create
        @player = Player.new(params[:player])

        if @player.save
            redirect_to(@player, :notice => 'Player was successfully created.')
        else
            render :action => "new"
        end
    end

    # PUT /players/1  
    def update
        @player = Player.find(params[:id])

        if @player.update_attributes(params[:player])
            redirect_to(@player, :notice => 'Player was successfully updated.')
        else
            render :action => "edit"
        end
    end

    # DELETE /players/1  
    def destroy
        @player = Player.find(params[:id])
        @player.destroy

        redirect_to(players_url)      
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    # GET /scores  
    def index
        @scores = Score.all
    end

    # GET /scores/1  
    def show
        @score = Score.find(params[:id])
    end

    # GET /scores/new  
    def new
        @score = Score.new
    end

    # GET /scores/edit
    def edit
        @score = Score.find(params[:id])
    end

    # POST /scores  
    def create
        @game = Game.find(params[:game_id])
        @score = @game.scores.create!(params[:score])

        if @score.save
            redirect_to(game_url(params[:game_id]))
        else
            render :new
        end
    end

    # PUT /scores/1  
    def update
        @score = Score.find(params[:id])
        @score.points = params[:points]
    
        if @score.save
            redirect_to(game_url(params[:game_id]))
        else
            render :edit
        end
    end

    # DELETE /scores/1  
    def destroy
        @score = Score.find(params[:id])
        @score.destroy
    
        redirect_to(game_url(params[:game_id]))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_date %><br />
    <%= f.datetime_select :game_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>

<section id="games">
<% @games.each do |game| %>
  <div class="game">
    <time><%= link_to game.game_date.strftime("%m/%d/%Y"), game_path(game) %></time>
    <% game.scores.sort!{|a,b| b.points <=> a.points}.each do |score| %>
      <div class="score">
        <span><%= score.player.name %></span>
        <span class="points"><%= score.points %></span>
      </div>
    <% end %>
    <div class="options"><%= link_to 'Delete', game, :confirm => 'Are you sure?', :method => :delete %></div>
  </div>
<% end %>
</section>

<br>
<nav>
<%= link_to 'New Game', new_game_path %>
<br>
<br>
<%= link_to 'Rankings', root_path %>
<br>
<br>
<%= link_to 'Players', players_path %>
</nav>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game date:</strong> <%= @game.game_date.strftime("%m/%d/%Y") %>
</p>

<h2>Scores</h2>
<div id="scores">
<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Score</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @game.scores.each do |score| %>
    <tr>
      <td><%= score.player.name %></td>
      <td><%= score.points %></td>
      <td>
        <%= link_to 'Edit', edit_game_score_path(@game, score) %>
        <%= link_to 'Delete', game_score_path(@game, score), :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<br>
<fieldset>
  <legend><strong>Add Score</strong></legend>
<% form_for [@game, Score.new()] do |f| %>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= select("score", "player_id", @players.collect {|p| [ p.name, p.id ] }, :prompt => false) %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="actions">
    <%= f.submit "Add Score" %>
  </div>
<% end %>
</fieldset>
<br>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
<h1>Bolf Tracker</h1>
<h2><%= @current_month.strftime("%B %Y") %> Rankings</h2>
<table>
  <thead>
    <tr>
      <th style="width: 160px;">Player</th>
      <th title="Wins">W</th>
      <th title="Losses">L</th>
      <th style="width: 50px;" title="Win Percentage">PCT</th>
      <th title="Total Points For">PF</th>
      <th title="Average Points Per Game">PPG</th>
    </tr>
  </thead>
  <tbody>
  <% @final_cur_month_players.each do |player| %>
    <% unless player.num_of_games.zero? %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.games_won %></td>
      <td><%= player.games_lost %></td>
      <td>
        <% if player.winning_pct == 1 %>
        1.000
        <% else %>
        <%= sprintf("%.3f", player.winning_pct).to_s[/.(.*)/m,1] %>
        <% end %>
      </td>
      <td><%= player.points %></td>
      <td><%= player.points_per_game %></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<h2><%= @previous_month.strftime("%B %Y") %> Rankings</h2>
<table>
  <thead>
    <tr>
      <th style="width: 160px;">Player</th>
      <th title="Wins">W</th>
      <th title="Losses">L</th>
      <th style="width: 50px;" title="Win Percentage">PCT</th>
      <th title="Total Points For">PF</th>
      <th title="Average Points Per Game">PPG</th>
    </tr>
  </thead>
  <tbody>
  <% @final_prev_month_players.each do |player| %>
    <% unless player.num_of_games.zero? %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.games_won %></td>
      <td><%= player.games_lost %></td>
      <td>
        <% if player.winning_pct == 1 %>
        1.000
        <% else %>
        <%= sprintf("%.3f", player.winning_pct).to_s[/.(.*)/m,1] %>
        <% end %>
      </td>
      <td><%= player.points %></td>
      <td><%= player.points_per_game %></td>
    </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<p>
<em>Rankings are determined in the following order: Win Percentage --> Points Per Game --> Total Points</em>
</p>
<%= link_to 'Games', games_path %>
<br>
<br>
<%= link_to 'Players', players_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Bolf Tracker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
      <script src="/javascripts/html5.js"></script>
    <![endif]-->
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Players</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Delete', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br>
<%= link_to 'New Player', new_player_path %>
<br>
<br>
<%= link_to 'Rankings', root_path %>
<br>
<br>
<%= link_to 'Games', games_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.text_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Score</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @scores.each do |score| %>
    <tr>
      <td><%= score.player.name %></td>
      <td><%= score.points %></td>
      <td>
        <%= link_to 'Edit', edit_game_score_path(@game, score) %>
        <%= link_to 'Delete', game_score_path(@game, score), :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<% form_tag(game_score_path, :method => "put") do %>
  <div class="field">
    <%= label_tag @score.player.name %>
  </div>
  <div class="field">
    <%= label_tag :points %><br />
    <%= text_field_tag :points, @score.points %>
  </div>
  <div class="actions">
    <%= submit_tag "Edit Score" %>
  </div>
<% end %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Game</th>
    <th>Points</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scores.each do |score| %>
  <tr>
    <td><%= score.player_id %></td>
    <td><%= score.game_id %></td>
    <td><%= score.points %></td>
    <td><%= link_to 'Show', score %></td>
    <td><%= link_to 'Edit', edit_score_path(score) %></td>
    <td><%= link_to 'Destroy', score.id, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @score.player_id %>
</p>

<p>
  <b>Game:</b>
  <%= @score.game_id %>
</p>

<p>
  <b>Points:</b>
  <%= @score.points %>
</p>


<%= link_to 'Edit', edit_game_score_path(@score) %> |
<%= link_to 'Back', game_scores_path %>